version: "3.9"

name: flask_app_demo
services:
  flask_app:
    container_name: app
    image: flask_app:latest
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@db:5432/users_db
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=users_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
    